// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.46.1_vite@7.0.6_@types+node@22.16.5_jiti@2.5.1_terser@5.4_3bb6a2eb309c88428d44007f83e99519/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.46.1_vite@7.0.6_@types+node@22.16.5_jiti@2.5.1_terser@5.4_3bb6a2eb309c88428d44007f83e99519/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.1_jwt-decode@4.0.0_magicast@0.3.5_vite@7.0.6_@types+node@22.16.5_jiti@2.5_a12f4f87f5affd725fb2d713acd9169c/node_modules/@nuxt/ui/dist/runtime/plugins/slideovers.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.1_jwt-decode@4.0.0_magicast@0.3.5_vite@7.0.6_@types+node@22.16.5_jiti@2.5_a12f4f87f5affd725fb2d713acd9169c/node_modules/@nuxt/ui/dist/runtime/plugins/modals.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.1_jwt-decode@4.0.0_magicast@0.3.5_vite@7.0.6_@types+node@22.16.5_jiti@2.5_a12f4f87f5affd725fb2d713acd9169c/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@7.0.6_@types+node@22.16.5_jiti@2.5.1_terser@5.43._66ebef085d2065b0c9435c32f01ae0c3/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.18.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node@22.16.5_@vue+compile_45d5e335db9b6a2ff09bb89cab3d5f72/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
